#!/usr/bin/env bun
/**
 * Bundles ghostty-web UMD build into a single browser-ready JS file
 * that exposes xterm.js-compatible globals (Terminal, FitAddon, etc.)
 *
 * The UMD build already inlines the WASM as a base64 data URL, so no
 * separate .wasm file needs to be served.
 *
 * Output: public/ghostty-web.bundle.js
 *
 * Globals exposed after init():
 *   window.Terminal              — drop-in for xterm.js Terminal
 *   window.FitAddon              — GhosttyWeb.FitAddon (direct constructor)
 *   window.Ghostty               — GhosttyWeb.Ghostty class
 *   window.createIsolatedGhostty — () => Promise<Ghostty> w/ its own WASM memory
 *   window.ghosttyReady          — Promise that resolves when WASM init is done
 *
 * Usage in HTML:
 *   <script src="/ghostty-web.bundle.js"></script>
 *   <script>
 *     await window.ghosttyReady;
 *     const term = new Terminal({ ... });
 *   </script>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const UMD_PATH = join(
  ROOT,
  "node_modules",
  "ghostty-web",
  "dist",
  "ghostty-web.umd.cjs",
);
const OUT_PATH = join(ROOT, "public", "ghostty-web.bundle.js");

const umdCode = readFileSync(UMD_PATH, "utf-8");

// The UMD assigns to globalThis.GhosttyWeb when loaded as a script tag.
// We wrap it in an IIFE and add global exposure + auto-init.
const bundle = `// AUTO-GENERATED by scripts/bundle-ghostty.ts — do not edit
// ghostty-web ${JSON.parse(readFileSync(join(ROOT, "node_modules", "ghostty-web", "package.json"), "utf-8")).version} bundled for browser
(function() {
"use strict";

// === ghostty-web UMD core ===
${umdCode}

// === xterm.js compatibility shim ===

// Expose xterm.js-compatible globals
window.Terminal = GhosttyWeb.Terminal;
window.FitAddon = GhosttyWeb.FitAddon;
window.Ghostty = GhosttyWeb.Ghostty;

// Per-Terminal WASM isolation. ghostty-web 0.4.0 ships a module-level singleton
// (the 'S' var inside the umd bundle) shared across all Terminal instances.
// Two Terminals → two handles in ONE WebAssembly.Memory → zig parser globals
// leak between them → wasm trap ("memory access out of bounds" at offset 0xf837)
// when adding a 2nd grid cell. createIsolatedGhostty() returns a Ghostty backed
// by its OWN WASM Instance (fresh Memory) so terminals can't corrupt each other.
//
// Each call recompiles+instantiates (~50ms). Acceptable for grid mode (handful of
// cells); not in any hot path.
window.createIsolatedGhostty = function() {
  // Reuse Ghostty.load()'s logic: it tries the embedded data: URL, file paths,
  // and ./ghostty-vt.wasm. Each call returns a brand-new Ghostty wrapping a
  // fresh WebAssembly.Instance — exactly what we want for per-terminal isolation.
  return GhosttyWeb.Ghostty.load();
};

// Auto-init WASM — consumers await window.ghosttyReady before creating terminals
window.wasmFailed = false;
if (typeof WebAssembly === "undefined" || typeof WebAssembly.instantiate !== "function") {
  console.warn("[ghostty-web] WebAssembly not supported — falling back to text mode");
  window.wasmFailed = true;
  window.ghosttyReady = Promise.reject(new Error("WebAssembly not supported"));
  window.ghosttyReady.catch(function() {});
} else {
  window.ghosttyReady = GhosttyWeb.init().then(function() {
    console.log("[ghostty-web] WASM initialized");
  }).catch(function(err) {
    console.error("[ghostty-web] WASM init failed:", err);
    window.wasmFailed = true;
    throw err;
  });
}

})();
`;

writeFileSync(OUT_PATH, bundle);

const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
console.log(`bundled ghostty-web → ${OUT_PATH} (${sizeKB} KB)`);
