#!/usr/bin/env bun
/**
 * Bundles client-side pure logic modules into a single browser-ready JS file.
 * Exposes functions on window.WP so index.html can call them directly.
 *
 * Output: public/wolfpack-lib.js
 *
 * Usage in HTML:
 *   <script src="/wolfpack-lib.js"></script>
 *   <script>
 *     const state = WP.captureScrollState(buffer);
 *   </script>
 */
import { join } from "node:path";
import { writeFileSync } from "node:fs";

const ROOT = join(import.meta.dirname, "..");
const ENTRY = join(ROOT, "src", "wolfpack-client-lib.ts");
const OUT_PATH = join(ROOT, "public", "wolfpack-lib.js");

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: "browser",
  format: "esm",
  minify: false,
});

if (!result.success) {
  console.error("bundle-client-lib failed:", result.logs);
  process.exit(1);
}

const esmCode = await result.outputs[0].text();

// Strip the export block; extract {localName, exportedName} pairs
// Handles Bun's "localName as exportedName" aliasing as well as plain names.
const exportMatch = esmCode.match(/export\s*\{([^}]+)\}/);
type ExportEntry = { local: string; exported: string };
const exportEntries: ExportEntry[] = exportMatch
  ? exportMatch[1].split(",").map(s => {
      const parts = s.trim().split(/\s+as\s+/);
      return parts.length === 2
        ? { local: parts[0].trim(), exported: parts[1].trim() }
        : { local: parts[0].trim(), exported: parts[0].trim() };
    }).filter(e => e.exported)
  : [];
const exportedNames = exportEntries.map(e => e.exported);
const coreCode = esmCode.replace(/export\s*\{[^}]*\};?\s*$/, "").trim();

// Verify all expected exports were found — catches silent breakage if Bun output format changes
const REQUIRED_EXPORTS = [
  "captureScrollState", "scrollTargetAfterResize", "serializeBufferTail",
  "shouldInterceptCopy", "encodeTerminalBinary", "shouldRehydrate",
  "addToGridState", "removeFromGridState", "suspendGridState", "resumeGridState",
  "classifyDisconnect", "handleViewerConflict", "handleControlGranted",
  "handleDisplaced", "prepareAutoTakeControl", "handleTakeControlClick",
  "CLOSE_CODE_DISPLACED", "CLOSE_CODE_SESSION_UNAVAILABLE", "CLOSE_CODE_NORMAL",
];
for (const name of REQUIRED_EXPORTS) {
  if (!exportedNames.includes(name)) {
    console.error(`bundle-client-lib: missing required export "${name}"`);
    process.exit(1);
  }
}

// Build WP object: use "exportedName: localName" to handle Bun's aliasing
const wpEntries = exportEntries.map(e =>
  e.local === e.exported ? e.exported : `${e.exported}: ${e.local}`
).join(", ");

const bundle = `// AUTO-GENERATED by scripts/bundle-client-lib.ts — do not edit
(function() {
"use strict";
${coreCode}
var WP = {${wpEntries}};
window.WP = WP;
})();
`;

writeFileSync(OUT_PATH, bundle);
const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
console.log(`bundled wolfpack-lib → ${OUT_PATH} (${sizeKB} KB)`);
