#!/usr/bin/env bun
/**
 * Bundles public/app.ts into public/app.bundle.js for browser consumption.
 * Uses Bun.build() with browser target. Output is global-scope (no IIFE)
 * so inline onclick handlers in index.html can call functions directly.
 *
 * Output: public/app.bundle.js
 *
 * Usage in HTML:
 *   <script src="/app.bundle.js"></script>
 */
import { join } from "node:path";
import { writeFileSync, existsSync } from "node:fs";

const ROOT = join(import.meta.dirname, "..");
const ENTRY = join(ROOT, "public", "app.ts");
const OUT_PATH = join(ROOT, "public", "app.bundle.js");

if (!existsSync(ENTRY)) {
  console.error(`bundle-app: ${ENTRY} not found — skipping`);
  process.exit(0);
}

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: "browser",
  format: "esm",
  minify: false,
});

if (!result.success) {
  console.error("bundle-app failed:", result.logs);
  process.exit(1);
}

const esmCode = await result.outputs[0].text();

// Strip export statements — app.ts functions must remain at global scope
// for onclick handlers in index.html to work
const code = esmCode.replace(/\bexport\s*\{[^}]*\};?\s*/g, "").trim();

const bundle = `// AUTO-GENERATED by scripts/bundle-app.ts — do not edit
${code}
`;

writeFileSync(OUT_PATH, bundle);
const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
console.log(`bundled app → ${OUT_PATH} (${sizeKB} KB)`);
