#!/usr/bin/env bun
/**
 * Bundles ghostty-web UMD build into a single browser-ready JS file
 * that exposes xterm.js-compatible globals (Terminal, FitAddon, etc.)
 *
 * The UMD build already inlines the WASM as a base64 data URL, so no
 * separate .wasm file needs to be served.
 *
 * Output: public/ghostty-web.bundle.js
 *
 * Globals exposed after init():
 *   window.Terminal        — drop-in for xterm.js Terminal
 *   window.FitAddon        — GhosttyWeb.FitAddon (direct constructor)
 *   window.ghosttyReady    — Promise that resolves when WASM init is done
 *
 * Usage in HTML:
 *   <script src="/ghostty-web.bundle.js"></script>
 *   <script>
 *     await window.ghosttyReady;
 *     const term = new Terminal({ ... });
 *   </script>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const UMD_PATH = join(
  ROOT,
  "node_modules",
  "ghostty-web",
  "dist",
  "ghostty-web.umd.cjs",
);
const OUT_PATH = join(ROOT, "public", "ghostty-web.bundle.js");

const umdCode = readFileSync(UMD_PATH, "utf-8");

// The UMD assigns to globalThis.GhosttyWeb when loaded as a script tag.
// We wrap it in an IIFE and add global exposure + auto-init.
const bundle = `// AUTO-GENERATED by scripts/bundle-ghostty.ts — do not edit
// ghostty-web ${JSON.parse(readFileSync(join(ROOT, "node_modules", "ghostty-web", "package.json"), "utf-8")).version} bundled for browser
(function() {
"use strict";

// === ghostty-web UMD core ===
${umdCode}

// === xterm.js compatibility shim ===

// Expose xterm.js-compatible globals
window.Terminal = GhosttyWeb.Terminal;
window.FitAddon = GhosttyWeb.FitAddon;

// Auto-init WASM — consumers await window.ghosttyReady before creating terminals
window.ghosttyReady = GhosttyWeb.init().then(function() {
  console.log("[ghostty-web] WASM initialized");
}).catch(function(err) {
  console.error("[ghostty-web] WASM init failed:", err);
  throw err;
});

})();
`;

writeFileSync(OUT_PATH, bundle);

const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
console.log(`bundled ghostty-web → ${OUT_PATH} (${sizeKB} KB)`);
