#!/usr/bin/env bun
/**
 * Syncs browser xterm assets from node_modules into public/, then generates
 * public-assets.ts — a module that embeds all files from public/ as a
 * Map<string, { content: string | Uint8Array; mime: string }>.
 *
 * Run: bun run scripts/gen-assets.ts
 * Output: public-assets.ts (project root)
 */
import { copyFileSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";

const PUBLIC_DIR = join(import.meta.dirname, "..", "public");
const OUT_FILE = join(import.meta.dirname, "..", "src", "public-assets.ts");
const NODE_MODULES_DIR = join(import.meta.dirname, "..", "node_modules");

const XTERM_ASSETS = [
  {
    source: join(NODE_MODULES_DIR, "@xterm", "xterm", "lib", "xterm.js"),
    target: join(PUBLIC_DIR, "xterm.min.js"),
  },
  {
    source: join(NODE_MODULES_DIR, "@xterm", "xterm", "css", "xterm.css"),
    target: join(PUBLIC_DIR, "xterm.css"),
  },
  {
    source: join(NODE_MODULES_DIR, "@xterm", "addon-fit", "lib", "addon-fit.js"),
    target: join(PUBLIC_DIR, "xterm-addon-fit.min.js"),
  },
  {
    source: join(NODE_MODULES_DIR, "@xterm", "addon-search", "lib", "addon-search.js"),
    target: join(PUBLIC_DIR, "xterm-addon-search.min.js"),
  },
  {
    source: join(NODE_MODULES_DIR, "@xterm", "addon-unicode11", "lib", "addon-unicode11.js"),
    target: join(PUBLIC_DIR, "xterm-addon-unicode11.min.js"),
  },
  {
    source: join(NODE_MODULES_DIR, "@xterm", "addon-webgl", "lib", "addon-webgl.js"),
    target: join(PUBLIC_DIR, "xterm-addon-webgl.min.js"),
  },
  {
    source: join(NODE_MODULES_DIR, "@xterm", "addon-web-links", "lib", "addon-web-links.js"),
    target: join(PUBLIC_DIR, "xterm-addon-web-links.min.js"),
  },
] as const;

const MIME_MAP: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".json": "application/json",
  ".js": "application/javascript",
  ".css": "text/css",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
};

const TEXT_EXTS = new Set([".html", ".json", ".js", ".css", ".svg", ".xml"]);

function isText(ext: string): boolean {
  return TEXT_EXTS.has(ext);
}

for (const asset of XTERM_ASSETS) {
  copyFileSync(asset.source, asset.target);
}

const files = readdirSync(PUBLIC_DIR).sort();
const entries: string[] = [];

for (const file of files) {
  const ext = extname(file).toLowerCase();
  const mime = MIME_MAP[ext] ?? "application/octet-stream";
  const filePath = join(PUBLIC_DIR, file);

  if (isText(ext)) {
    const content = readFileSync(filePath, "utf-8");
    // Use JSON.stringify to safely embed the string
    entries.push(
      `  [${JSON.stringify(file)}, { content: ${JSON.stringify(content)}, mime: ${JSON.stringify(mime)} }]`,
    );
  } else {
    // Binary: embed as base64, decode at import time
    const buf = readFileSync(filePath);
    const b64 = buf.toString("base64");
    entries.push(
      `  [${JSON.stringify(file)}, { content: _b64(${JSON.stringify(b64)}), mime: ${JSON.stringify(mime)} }]`,
    );
  }
}

const output = `// AUTO-GENERATED by scripts/gen-assets.ts — do not edit
// Embeds all files from public/ for bun compile single-binary distribution.

function _b64(s: string): Uint8Array {
  return Buffer.from(s, "base64");
}

export const assets = new Map<string, { content: string | Uint8Array; mime: string }>([
${entries.join(",\n")},
]);
`;

writeFileSync(OUT_FILE, output);
console.log(`generated ${OUT_FILE} (${files.length} files embedded)`);
